# Generated by Django 5.0.1 on 2024-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_artical_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='is_homepage',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='layout',
        ),
        migrations.AddField(
            model_name='artical',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artical',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
