# Generated by Django 5.0.1 on 2024-02-10 00:05

import home.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_artical_options_alter_catagory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=home.helpers.get_file_path, verbose_name='Contact list'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='artical',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
